"""
Data models for Enhanced Architecture Analysis System

This package contains all dataclass models used throughout the analysis system.
"""

from .architecture_models import (
    ArchitectureAnalysis,
    CodebaseStatistics,
    DetectedPattern,
    Layer,
    Component,
    LayerConnection,
    Technology,
    Vulnerability,
    DataFlowScenario,
    FlowStep,
    Bottleneck,
    DependencyAnalysis,
    DependencyTree,
    DependencyNode,
    CircularDependency,
    OutdatedPackage,
    DependencyVulnerability,
    LicenseIssue,
    QualityMetrics,
    ComplexityMetrics,
    Hotspot,
    TechnicalDebt,
    DuplicatedBlock,
    Recommendation,
    CodeLocation,
    Visualization,
    VisualizationMetadata,
    LegacyArchitecture,
)

__all__ = [
    "ArchitectureAnalysis",
    "CodebaseStatistics",
    "DetectedPattern",
    "Layer",
    "Component",
    "LayerConnection",
    "Technology",
    "Vulnerability",
    "DataFlowScenario",
    "FlowStep",
    "Bottleneck",
    "DependencyAnalysis",
    "DependencyTree",
    "DependencyNode",
    "CircularDependency",
    "OutdatedPackage",
    "DependencyVulnerability",
    "LicenseIssue",
    "QualityMetrics",
    "ComplexityMetrics",
    "Hotspot",
    "TechnicalDebt",
    "DuplicatedBlock",
    "Recommendation",
    "CodeLocation",
    "Visualization",
    "VisualizationMetadata",
    "LegacyArchitecture",
]
